# Generated by Django 5.0.2 on 2024-02-07 13:21

import django.db.models.deletion
import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre_name', models.CharField(max_length=50)),
                ('slug', models.SlugField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('book_id', models.AutoField(primary_key=True, serialize=False)),
                ('slug', models.SlugField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=255)),
                ('publication_date', models.DateField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField()),
                ('cover_image_url', models.ImageField(default='images/default.png', upload_to='images/')),
                ('in_stock', models.BooleanField(default=True)),
                ('genre_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Wanderapp.genre')),
            ],
            managers=[
                ('books', django.db.models.manager.Manager()),
            ],
        ),
    ]
